default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["BACKEND_DATABASE_USER"] %>
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
